### PR TITLE
Feature/164 misc bugs

### LINKED ISSUE #164: Melissa bugs
~~Creating a new site:~~

~~New site form should have all required fields in section 1~~
~~After creating a new site, should be navigated to section two. Since all of section 1 will be complete when creating the site.~~

Delegated above to https://github.com/globalmangrovewatch/gmw-users/issues/188

Section 3:

Question 3.3 is not required

### PR DESCRIPTION
**Pull request by mmnoo**
closes #164 

- make question 3.3 not required, show rest as required with asterisk
- make all questions show as required with asterisk for project details form

### CODE REVIEW

File: mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js [hunk 1]
```diff
@@ -32,7 +35,7 @@ const RestorationAimsForm = () => {
   const validationSchema = yup.object({
     ecologicalAims: multiselectWithOtherValidation,
     socioEconomicAims: multiselectWithOtherValidation,
-    otherAims: multiselectWithOtherValidation
+    otherAims: multiselectWithOtherValidationNoMinimum
```
Comment (mmnoo) [inline mrtt-ui/src/components/RestorationAimsForm/RestorationAimsForm.js:38]: sweet! No work for me!

**Review by julia-rom — APPROVED** [review]
